"""Small BED and interval helpers used by peak2anno commands."""

from __future__ import annotations

import bisect
import csv
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Optional, Sequence, Tuple


REGION_RE = re.compile(r"^(.+?)[\:\*\-=/\^;_%\$,](\d+)[\:\*\-=/\^;_%\$,](\d+)$")


@dataclass(frozen=True)
class BedRecord:
    """Represent one BED-like interval.

    Args:
        chrom (str): Chromosome or contig name.
        start (int): Zero-based half-open start coordinate.
        end (int): Zero-based half-open end coordinate.
        fields (Tuple[str, ...]): Original parsed fields.
    """

    chrom: str
    start: int
    end: int
    fields: Tuple[str, ...]
    source_start: Optional[int] = None
    source_end: Optional[int] = None

    @property
    def length(self) -> int:
        """Return interval length in base pairs."""
        return max(0, self.end - self.start)

    @property
    def name(self) -> str:
        """Return BED column 4 or '.' when absent."""
        return self.fields[3] if len(self.fields) > 3 and self.fields[3] else "."

    @property
    def score(self) -> str:
        """Return BED column 5 or '.' when absent."""
        return self.fields[4] if len(self.fields) > 4 and self.fields[4] else "."

    @property
    def strand(self) -> str:
        """Return BED column 6 or '.' when absent."""
        return self.fields[5] if len(self.fields) > 5 and self.fields[5] else "."

    @property
    def gene_id(self) -> str:
        """Return BED column 7 or '.' when absent."""
        return self.fields[6] if len(self.fields) > 6 and self.fields[6] else "."

    @property
    def transcript_id(self) -> str:
        """Return BED column 8 or '.' when absent."""
        return self.fields[7] if len(self.fields) > 7 and self.fields[7] else "."

    @property
    def gene_type(self) -> Optional[str]:
        """Return BED column 9 when present."""
        return self.fields[8] if len(self.fields) > 8 and self.fields[8] else None


@dataclass(frozen=True)
class InputRegion:
    """Represent one input row with genomic coordinates.

    Args:
        chrom (str): Chromosome or contig name.
        start (int): Zero-based half-open start coordinate.
        end (int): Zero-based half-open end coordinate.
        values (Tuple[str, ...]): Original table values.
    """

    chrom: str
    start: int
    end: int
    values: Tuple[str, ...]

    @property
    def length(self) -> int:
        """Return interval length in base pairs."""
        return max(0, self.end - self.start)

    @property
    def region_name(self) -> str:
        """Return a chr:start-end region string."""
        return f"{self.chrom}:{self.start}-{self.end}"


def write_bedtools_review_script(
    input_path: Path,
    reference_path: Path,
    promoter_up: int,
    enhancer: int,
    promoter_down: int,
) -> Path:
    """Write a standalone raw-BED bedtools review script.

    The generated script supports mode ``1`` (one wide window) and mode ``2``
    (promoter first, enhancer second).  It emits a package-compatible
    peak-to-gene table while keeping the bedtools, awk, and sort steps easy to
    inspect.
    """
    script_path = Path("bedtools-peak2anno.sh").resolve()
    input_text = shlex.quote(str(input_path.expanduser().resolve()))
    reference_text = shlex.quote(str(reference_path.expanduser().resolve()))
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "export LC_ALL=C",
        "",
        "# Generated by sjcab_peak2anno for review/reproduction.",
        "# Input must be BED-like with chromosome/start/end in columns 1-3.",
        "# Reference must contain TSS-like BED records with name, strand, and gene ID.",
        "# Usage: ./bedtools-peak2anno.sh [1|2] [output.tsv]",
        "MODE=${1:-2}",
        "OUTPUT=${2:-peak2gene.bedtools.tsv}",
        f"INPUT={input_text}",
        f"REFERENCE={reference_text}",
        f"PROMOTER_UP={promoter_up}",
        f"ENHANCER={enhancer}",
        f"PROMOTER_DOWN={promoter_down}",
        "",
        "case \"$MODE\" in 1|2) ;; *) echo 'MODE must be 1 or 2' >&2; exit 2 ;; esac",
        "command -v bedtools >/dev/null || { echo 'bedtools is required' >&2; exit 127; }",
        "WORK=$(mktemp -d -t sjcab-peak2anno-script.XXXXXX)",
        "trap 'rm -rf \"$WORK\"' EXIT",
        "awk 'BEGIN{OFS=\"\\t\"} !/^#/ && NF >= 3 {print $1,$2,$3,NR}' \"$INPUT\" > \"$WORK/query.bed\"",
        "",
        "# Emit query_id, class, reference_name, gene_id, distance.",
        "classify_promoter='",
        "BEGIN{OFS=\"\\t\"}",
        "function abs(x){return x < 0 ? -x : x}",
        "function max(a,b){return a > b ? a : b}",
        "{",
        "  qid=$4; rs=$6; re=$7; name=$8; strand=$10; gid=$11",
        "  if ($3 <= rs) {d=rs-$3; side=\"left\"} else if ($2 >= re) {d=$2-re; side=\"right\"} else {d=0; side=\"overlap\"}",
        "  allowed=max(PROMOTER_UP,PROMOTER_DOWN)",
        "  if (side == \"left\" && strand == \"+\") allowed=PROMOTER_UP",
        "  if (side == \"right\" && strand == \"+\") allowed=PROMOTER_DOWN",
        "  if (side == \"left\" && strand == \"-\") allowed=PROMOTER_DOWN",
        "  if (side == \"right\" && strand == \"-\") allowed=PROMOTER_UP",
        "  if (d <= allowed) print qid,\"promoter\",name,gid,d",
        "}",
        "'",
        "",
    ]
    lines.extend([
        "if [[ \"$MODE\" == 1 ]]; then",
        "  bedtools window -a \"$WORK/query.bed\" -b \"$REFERENCE\" -w \"$((ENHANCER + 1))\" \\",
        "    > \"$WORK/wide.tsv\"",
        "  awk -v PROMOTER_UP=\"$PROMOTER_UP\" -v PROMOTER_DOWN=\"$PROMOTER_DOWN\" \"$classify_promoter\" \"$WORK/wide.tsv\" > \"$WORK/promoters.tsv\"",
        "  cut -f1 \"$WORK/promoters.tsv\" | sort -nu > \"$WORK/promoter_ids.txt\"",
        "  awk 'NR==FNR{seen[$1]=1; next} !($4 in seen)' \"$WORK/promoter_ids.txt\" \"$WORK/wide.tsv\" \\",
        "    | awk -v ENHANCER=\"$ENHANCER\" 'BEGIN{OFS=\"\\t\"} {d=($3 <= $6 ? $6-$3+1 : ($2 >= $7 ? $2-$7+1 : 0)); if (d <= ENHANCER) print $4,\"enhancer\",$8,$11,d}' > \"$WORK/enhancers.tsv\"",
        "else",
        "  bedtools window -a \"$WORK/query.bed\" -b \"$REFERENCE\" -w \"$(( (PROMOTER_UP > PROMOTER_DOWN ? PROMOTER_UP : PROMOTER_DOWN) + 1 ))\" \\",
        "    | awk -v PROMOTER_UP=\"$PROMOTER_UP\" -v PROMOTER_DOWN=\"$PROMOTER_DOWN\" \"$classify_promoter\" > \"$WORK/promoters.tsv\"",
        "  cut -f1 \"$WORK/promoters.tsv\" | sort -nu > \"$WORK/promoter_ids.txt\"",
        "  awk 'NR==FNR{seen[$1]=1; next} !($4 in seen)' \"$WORK/promoter_ids.txt\" \"$WORK/query.bed\" > \"$WORK/no_promoter.bed\"",
        "  bedtools window -a \"$WORK/no_promoter.bed\" -b \"$REFERENCE\" -w \"$((ENHANCER + 1))\" \\",
        "    | awk -v ENHANCER=\"$ENHANCER\" 'BEGIN{OFS=\"\\t\"} {d=($3 <= $6 ? $6-$3+1 : ($2 >= $7 ? $2-$7+1 : 0)); if (d <= ENHANCER) print $4,\"enhancer\",$8,$11,d}' > \"$WORK/enhancers.tsv\"",
        "fi",
        "cat \"$WORK/promoters.tsv\" \"$WORK/enhancers.tsv\" > \"$WORK/matches.tsv\"",
        "awk -F $'\\t' 'BEGIN{OFS=FS} {print $1,$2,$3}' \"$WORK/matches.tsv\" | sort -t $'\\t' -k1,1n -k2,2 -k3,3 -u | awk -F $'\\t' 'BEGIN{OFS=FS} function flush(){if(qid!=\"\") print qid,cat,value} {if($1!=qid || $2!=cat){flush(); qid=$1; cat=$2; value=$3} else {value=value (value==\"\" ? \"\" : \",\") $3}} END{flush()}' > \"$WORK/names.tsv\"",
        "awk -F $'\\t' 'BEGIN{OFS=FS} {print $1,$2,$4}' \"$WORK/matches.tsv\" | sort -t $'\\t' -k1,1n -k2,2 -k3,3 -u | awk -F $'\\t' 'BEGIN{OFS=FS} function flush(){if(qid!=\"\") print qid,cat,value} {if($1!=qid || $2!=cat){flush(); qid=$1; cat=$2; value=$3} else {value=value (value==\"\" ? \"\" : \",\") $3}} END{flush()}' > \"$WORK/ids.tsv\"",
        "bedtools closest -a \"$WORK/query.bed\" -b \"$REFERENCE\" -d -t first | awk '{print $4,$8,$11,$NF}' OFS=$'\\t' > \"$WORK/closest.tsv\"",
        "awk -F $'\\t' -v OFS=$'\\t' -v NAMES=\"$WORK/names.tsv\" -v IDS=\"$WORK/ids.tsv\" -v CLOSEST=\"$WORK/closest.tsv\" '",
        "BEGIN { while ((getline line < NAMES) > 0) { split(line,a,FS); names[a[1] SUBSEP a[2]]=a[3] } close(NAMES); while ((getline line < IDS) > 0) { split(line,a,FS); ids[a[1] SUBSEP a[2]]=a[3] } close(IDS); while ((getline line < CLOSEST) > 0) { split(line,a,FS); closest[a[1]]=a[2]; closest_id[a[1]]=a[3]; closest_dist[a[1]]=a[4] } close(CLOSEST) }",
        "{ q=$4; p=names[q SUBSEP \"promoter\"]; if(p==\"\") p=\".\"; pi=ids[q SUBSEP \"promoter\"]; if(pi==\"\") pi=\".\"; e=names[q SUBSEP \"enhancer\"]; if(e==\"\") e=\".\"; ei=ids[q SUBSEP \"enhancer\"]; if(ei==\"\") ei=\".\"; g=closest[q]; if(g==\"\") g=\".\"; gi=closest_id[q]; if(gi==\"\") gi=\".\"; d=closest_dist[q]; if(d==\"\") d=\".\"; print $1,$2,$3,p,pi,e,ei,g,gi,d }' \"$WORK/query.bed\" > \"$WORK/body.tsv\"",
        "printf 'chr\\tstart\\tend\\tGene_%skb\\tGencode_ids\\tGene_%s-%skb\\tGencode_ids\\tClosest_Gene\\tGencode_id\\tDistance\\n' \"$((PROMOTER_UP / 1000))\" \"$((PROMOTER_UP / 1000))\" \"$((ENHANCER / 1000))\" > \"$OUTPUT\"",
        "cat \"$WORK/body.tsv\" >> \"$OUTPUT\"",
        "echo \"Wrote $OUTPUT\" >&2",
        "",
    ])
    script_path.write_text("\n".join(lines), encoding="utf-8")
    script_path.chmod(0o755)
    return script_path


def external_window_records(
    regions: Sequence[InputRegion],
    records: Sequence[BedRecord],
    distance: int,
    backend: str,
) -> Dict[int, List[BedRecord]]:
    """Run one batched bedtools window query.

    The fourth query column is an internal row ID, so callers can reconstruct
    the same per-input-region results as the Python interval index.
    """
    if not regions or not records:
        return {}
    ref_width = max(len(record.fields) for record in records)
    with tempfile.TemporaryDirectory(prefix="sjcab-peak2anno-backend-") as temp:
        root = Path(temp)
        query_path = root / "query.bed"
        reference_path = root / "reference.bed"
        with query_path.open("w", encoding="utf-8") as handle:
            for index, region in enumerate(regions):
                handle.write(f"{region.chrom}\t{region.start}\t{region.end}\t{index}\n")
        with reference_path.open("w", encoding="utf-8") as handle:
            for record in records:
                fields = list(record.fields) + ["."] * (ref_width - len(record.fields))
                handle.write("\t".join(fields) + "\n")

        if backend == "bedtools":
            executable = shutil.which("bedtools")
            if executable is None:
                raise FileNotFoundError("bedtools was not found on PATH")
            command = [
                executable,
                "window",
                "-a",
                str(query_path),
                "-b",
                str(reference_path),
                "-w",
                str(max(0, distance) + 1),
            ]
            process = subprocess.Popen(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            if process.stdout is None:
                raise RuntimeError("could not read bedtools output")
            lines: Iterable[str] = process.stdout
        else:
            raise ValueError(f"Unsupported external backend: {backend}")

        result: Dict[int, List[BedRecord]] = {}
        for line in lines:
            fields = split_fields(line)
            if len(fields) < 4 + ref_width:
                continue
            try:
                query_id = int(fields[3])
            except ValueError:
                continue
            reference_fields = tuple(fields[4 : 4 + ref_width])
            result.setdefault(query_id, []).append(
                BedRecord(
                    reference_fields[0],
                    int(reference_fields[1]),
                    int(reference_fields[2]),
                    reference_fields,
                )
            )
        if backend == "bedtools":
            stderr = process.stderr.read() if process.stderr is not None else ""
            return_code = process.wait()
            if return_code:
                raise subprocess.CalledProcessError(return_code, process.args, stderr=stderr)
        return result


class IntervalIndex:
    """Chromosome-indexed interval collection with overlap queries."""

    def __init__(self, records: Iterable[BedRecord]):
        """Build an interval index.

        Args:
            records (Iterable[BedRecord]): BED-like records to index.
        """
        grouped: Dict[str, List[BedRecord]] = {}
        for record in records:
            if record.end <= record.start:
                continue
            grouped.setdefault(record.chrom, []).append(record)
        self.records_by_chrom: Dict[str, List[BedRecord]] = {}
        self.starts_by_chrom: Dict[str, List[int]] = {}
        self.prefix_max_end_by_chrom: Dict[str, List[int]] = {}
        for chrom, chrom_records in grouped.items():
            chrom_records.sort(key=lambda item: (item.start, item.end))
            self.records_by_chrom[chrom] = chrom_records
            self.starts_by_chrom[chrom] = [item.start for item in chrom_records]
            prefix: List[int] = []
            max_end = 0
            for item in chrom_records:
                max_end = max(max_end, item.end)
                prefix.append(max_end)
            self.prefix_max_end_by_chrom[chrom] = prefix

    def query(self, chrom: str, start: int, end: int) -> Iterator[BedRecord]:
        """Yield records overlapping a query interval.

        Args:
            chrom (str): Chromosome or contig name.
            start (int): Query start coordinate.
            end (int): Query end coordinate.

        Yields:
            BedRecord: Records with positive overlap.
        """
        records = self.records_by_chrom.get(chrom)
        if not records or end <= start:
            return
        starts = self.starts_by_chrom[chrom]
        prefix = self.prefix_max_end_by_chrom[chrom]
        idx = bisect.bisect_left(starts, end)
        for offset in range(idx - 1, -1, -1):
            if records[offset].end > start:
                yield records[offset]
            if offset > 0 and prefix[offset - 1] <= start:
                break

    def records_for_chrom(self, chrom: str) -> Sequence[BedRecord]:
        """Return sorted records for a chromosome."""
        return self.records_by_chrom.get(chrom, ())

    def query_window(self, chrom: str, start: int, end: int, distance: int) -> Iterator[BedRecord]:
        """Yield records within a fixed distance of a query interval.

        The older implementation scanned every record on a chromosome for
        each query.  This indexed window keeps the same overlap semantics but
        restricts the scan to the coordinate neighborhood used by peak2gene.
        """
        records = self.records_by_chrom.get(chrom)
        if not records:
            return
        starts = self.starts_by_chrom[chrom]
        lower = start - max(0, distance)
        upper = end + max(0, distance)
        left = max(0, bisect.bisect_left(starts, lower) - 1)
        right = bisect.bisect_right(starts, upper)
        for record in records[left:right]:
            if distance_bp(start, end, record.start, record.end) <= distance:
                yield record

    def nearest_candidates(self, chrom: str, start: int, end: int) -> Iterator[BedRecord]:
        """Yield overlap and immediate flanking records for closest queries."""
        records = self.records_by_chrom.get(chrom)
        if not records:
            return
        starts = self.starts_by_chrom[chrom]
        right = bisect.bisect_left(starts, start)
        flank_indexes = {max(0, right - 1), min(len(records) - 1, right)}
        # Keep all records at a flank coordinate.  bedtools ``closest -t
        # first`` resolves equal-distance ties using reference-file order.
        for index in tuple(flank_indexes):
            flank_start = records[index].start
            flank_end = records[index].end
            offset = index - 1
            while offset >= 0 and (records[offset].start, records[offset].end) == (flank_start, flank_end):
                flank_indexes.add(offset)
                offset -= 1
            offset = index + 1
            while offset < len(records) and (records[offset].start, records[offset].end) == (flank_start, flank_end):
                flank_indexes.add(offset)
                offset += 1
        candidates = [records[index] for index in sorted(flank_indexes)]
        candidates.extend(self.query(chrom, start, end))
        seen = set()
        for record in candidates:
            if record in seen:
                continue
            seen.add(record)
            yield record


def split_fields(line: str) -> List[str]:
    """Split a table line into fields while preferring tab separation."""
    text = line.rstrip("\n")
    if "\t" in text:
        return text.split("\t")
    return text.split()


def is_int(text: str) -> bool:
    """Return whether text can be parsed as an integer."""
    try:
        int(text)
    except ValueError:
        return False
    return True


def _region_matches(text: str, delimiter: str = "auto") -> bool:
    """Return whether text contains a valid region using the selected delimiter."""
    if delimiter and delimiter != "auto":
        separator = delimiter.encode().decode("unicode_escape")
        fields = text.split(separator)
        return len(fields) == 3 and all(field.isdigit() for field in fields[1:])
    return REGION_RE.match(text) is not None


def parse_region(text: str, delimiter: str = "auto") -> Tuple[str, int, int]:
    """Parse a region string with common delimiters, such as ``chr1:100-200``.

    Args:
        text (str): Region text.

    Returns:
        Tuple[str, int, int]: Chromosome, start, and end.

    Raises:
        ValueError: If the text is not a supported region string.
    """
    if delimiter and delimiter != "auto":
        fields = text.split(delimiter.encode().decode("unicode_escape"))
        if len(fields) == 3 and all(field.isdigit() for field in fields[1:]):
            return fields[0], int(fields[1]), int(fields[2])
        match = None
    else:
        match = REGION_RE.match(text)
    if not match:
        raise ValueError(f"Expected region string like chr1:100-200, found {text!r}")
    chrom, start, end = match.groups()
    return chrom, int(start), int(end)


def normalize_header(header: Sequence[str]) -> Dict[str, int]:
    """Map lower-case column names to positions."""
    return {name.lower(): idx for idx, name in enumerate(header)}


def coordinate_columns(header: Sequence[str]) -> Tuple[Optional[int], Optional[int], Optional[int], Optional[int]]:
    """Return column positions for region or chrom/start/end fields."""
    columns = normalize_header(header)
    region_idx = columns.get("region")
    chrom_idx = None
    for name in ("chr", "chrom", "chromosome"):
        if name in columns:
            chrom_idx = columns[name]
            break
    start_idx = None
    for name in ("start", "chromstart"):
        if name in columns:
            start_idx = columns[name]
            break
    end_idx = None
    for name in ("end", "chromend"):
        if name in columns:
            end_idx = columns[name]
            break
    return region_idx, chrom_idx, start_idx, end_idx


def read_regions(
    path: Path,
    header: str = "auto",
    input_format: str = "auto",
    columns: Optional[Tuple[int, int, int]] = None,
    region_column: int = 0,
    txt_delimiter: str = "auto",
) -> Tuple[List[str], List[InputRegion]]:
    """Read BED or TSV rows and extract genomic coordinates.

    Args:
        path (Path): Input BED or TSV path.
        header (str): One of ``auto``, ``yes``, or ``no``.

    Returns:
        Tuple[List[str], List[InputRegion]]: Output header and parsed regions.

    Raises:
        ValueError: If coordinates cannot be resolved.
    """
    if header not in {"auto", "yes", "no"}:
        raise ValueError("header must be one of: auto, yes, no")
    if input_format not in {"auto", "bed", "txt", "txtnohead"}:
        raise ValueError("input format must be one of: auto, bed, txt, txtnohead")
    rows: List[List[str]] = []
    with path.open("r", encoding="utf-8") as handle:
        for raw in handle:
            if not raw.strip() or raw.startswith("#") or raw.startswith("track") or raw.startswith("browser"):
                continue
            rows.append(split_fields(raw))
    if not rows:
        raise ValueError(f"No data rows found in {path}")

    first = rows[0]
    if not 0 <= region_column < len(first):
        raise ValueError(f"Region column {region_column} is not present in {path}")
    coordinate_hint = columns or (0, 1, 2)
    inferred_bed = (
        max(coordinate_hint) < len(first)
        and is_int(first[coordinate_hint[1]])
        and is_int(first[coordinate_hint[2]])
    )
    if input_format == "bed":
        has_header = header == "yes" or (header == "auto" and not inferred_bed)
    elif input_format in {"txt", "txtnohead"}:
        has_header = input_format == "txt" and (header == "yes" or (header == "auto" and not _region_matches(first[region_column], txt_delimiter)))
    else:
        has_header = header == "yes" or (
            header == "auto"
            and not (inferred_bed or _region_matches(first[region_column], txt_delimiter))
        )
    if has_header:
        out_header = first
        data_rows = rows[1:]
    else:
        width = max(len(row) for row in rows)
        # Do not assume BED6 metadata for headerless BED.  BED3 is the only
        # required shape; any additional columns receive generic names.
        default_names = ["chr", "start", "end"]
        if input_format in {"txt", "txtnohead"}:
            default_names = ["Region"]
        out_header = default_names[: min(width, len(default_names))]
        if width > len(out_header):
            out_header.extend(f"field{i}" for i in range(len(out_header) + 1, width + 1))
        data_rows = rows

    region_idx, chrom_idx, start_idx, end_idx = coordinate_columns(out_header)
    if input_format in {"txt", "txtnohead"} or (input_format == "auto" and not inferred_bed):
        region_idx = region_column
        chrom_idx = start_idx = end_idx = None
    elif columns is not None:
        chrom_idx, start_idx, end_idx = columns
        region_idx = None
    regions: List[InputRegion] = []
    for row_number, row in enumerate(data_rows, start=2 if has_header else 1):
        if len(row) < len(out_header):
            row = row + ["."] * (len(out_header) - len(row))
        if region_idx is not None:
            chrom, start, end = parse_region(row[region_idx], txt_delimiter)
        elif chrom_idx is not None and start_idx is not None and end_idx is not None:
            chrom = row[chrom_idx]
            start = int(row[start_idx])
            end = int(row[end_idx])
        else:
            raise ValueError(
                f"Could not find Region or chr/start/end columns in {path}; header={out_header!r}"
            )
        if end < start:
            raise ValueError(f"End before start at {path}:{row_number}: {row!r}")
        regions.append(InputRegion(chrom=chrom, start=start, end=end, values=tuple(row)))
    return out_header, regions


def detect_output_format(
    path: Path,
    header: str = "auto",
    input_format: str = "auto",
    columns: Optional[Tuple[int, int, int]] = None,
    region_column: int = 0,
    txt_delimiter: str = "auto",
) -> str:
    """Return the default output mode implied by an input file."""
    if input_format == "bed":
        return "bed"
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for raw in handle:
            if raw.strip() and not raw.startswith(("#", "track", "browser")):
                rows.append(split_fields(raw))
                break
    if not rows:
        raise ValueError(f"No data rows found in {path}")
    first = rows[0]
    if input_format in {"txt", "txtnohead"}:
        if input_format == "txtnohead":
            return "txtnohead"
        if header == "yes":
            return "txt"
        if header == "no":
            return "txtnohead"
        return "txt" if not _region_matches(first[region_column], txt_delimiter) else "txtnohead"
    coordinate_hint = columns or (0, 1, 2)
    is_bed = (
        max(coordinate_hint) < len(first)
        and is_int(first[coordinate_hint[1]])
        and is_int(first[coordinate_hint[2]])
    ) or (
        len(first) >= 3
        and first[1].lower() in {"start", "chromstart"}
        and first[2].lower() in {"end", "chromend"}
    )
    if is_bed:
        return "bed"
    if header == "yes":
        return "txt"
    if header == "no":
        return "txtnohead"
    return "txt" if not _region_matches(first[region_column], txt_delimiter) else "txtnohead"


def read_bed_records(
    path: Path,
    gene_type: str = "nomicro",
    as_tss: bool = False,
) -> List[BedRecord]:
    """Read BED-like records with optional gene-type filtering.

    Args:
        path (Path): BED path.
        gene_type (str): ``all``, a single type, comma-separated types, or ``nomicro``.
        as_tss (bool): Convert gene intervals into one-base TSS intervals using strand.

    Returns:
        List[BedRecord]: Parsed records.

    Raises:
        ValueError: If a requested gene type cannot be evaluated.
    """
    wanted_types = expand_gene_types(gene_type)
    records: List[BedRecord] = []
    saw_gene_type = False
    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw in enumerate(handle, start=1):
            if not raw.strip() or raw.startswith("#") or raw.startswith("track") or raw.startswith("browser"):
                continue
            fields = split_fields(raw)
            if len(fields) < 3 or not is_int(fields[1]) or not is_int(fields[2]):
                continue
            if len(fields) > 8:
                saw_gene_type = True
            if wanted_types is not None:
                if len(fields) <= 8:
                    continue
                if fields[8] not in wanted_types:
                    continue
            start = int(fields[1])
            end = int(fields[2])
            if as_tss and end > start + 1:
                strand = fields[5] if len(fields) > 5 else "."
                if strand == "-":
                    # Keep the historical voom/GENCODE TSS coordinate:
                    # plus-strand TSS is the BED start, minus-strand TSS
                    # is the BED end.  This makes the strand-aware TSS
                    # point consistent with the reported distance column.
                    start = end
                end = start + 1
            if end < start:
                raise ValueError(f"End before start at {path}:{line_number}")
            tfields = tuple([fields[0], str(start), str(end)] + fields[3:])
            records.append(
                BedRecord(
                    chrom=fields[0],
                    start=start,
                    end=end,
                    fields=tfields,
                    source_start=int(fields[1]),
                    source_end=int(fields[2]),
                )
            )
    if wanted_types is not None and not saw_gene_type:
        raise ValueError(
            f"{path} does not have BED column 9 gene_type; cannot apply --gene-type {gene_type!r}"
        )
    return records


def expand_gene_types(gene_type: str) -> Optional[set[str]]:
    """Expand a gene-type selector into accepted BED column 9 values."""
    if gene_type == "all":
        return None
    if gene_type == "nomicro":
        return {
            "bidirectional_promoter_lncrna",
            "lincRNA",
            "macro_lncRNA",
            "processed_pseudogene",
            "processed_transcript",
            "protein_coding",
            "transcribed_processed_pseudogene",
            "transcribed_unitary_pseudogene",
            "transcribed_unprocessed_pseudogene",
            "translated_unprocessed_pseudogene",
        }
    return {item.strip() for item in gene_type.split(",") if item.strip()}


def parse_distance(text: str) -> int:
    """Parse a distance such as 2000, 2kb, or 1Mb into base pairs."""
    value = text.strip()
    match = re.match(r"^(\d+(?:\.\d+)?)(bp|b|kb|k|mb|m)?$", value, flags=re.IGNORECASE)
    if not match:
        raise ValueError(f"Unsupported distance value: {text!r}")
    number = float(match.group(1))
    suffix = (match.group(2) or "").lower()
    if suffix in {"", "b", "bp"}:
        pass
    elif suffix in {"k", "kb"}:
        number *= 1000
    elif suffix in {"m", "mb"}:
        number *= 1000000
    return int(number)


def format_distance(value: int) -> str:
    """Format a distance for legacy-style column labels."""
    if value % 1000000 == 0:
        return f"{value // 1000000}Mb"
    if value % 1000 == 0:
        return f"{value // 1000}kb"
    return f"{value}bp"


@dataclass(frozen=True)
class OverlapCutoff:
    """Represent an overlap threshold as base pairs or query fraction."""

    value: float
    mode: str

    def passes(self, overlap_bp: int, query_length: int) -> bool:
        """Return whether an overlap satisfies this threshold."""
        if self.mode == "fraction":
            if query_length <= 0:
                return False
            return overlap_bp / query_length >= self.value
        return overlap_bp >= self.value


def parse_overlap_cutoff(text: str) -> OverlapCutoff:
    """Parse overlap cutoff text such as 1bp, 10bp, 0.1, or 10%."""
    value = text.strip()
    if value.endswith("%"):
        return OverlapCutoff(float(value[:-1]) / 100.0, "fraction")
    if value.lower().endswith("bp"):
        return OverlapCutoff(float(value[:-2]), "bp")
    number = float(value)
    if 0 < number < 1:
        return OverlapCutoff(number, "fraction")
    return OverlapCutoff(number, "bp")


def overlap_bp(a_start: int, a_end: int, b_start: int, b_end: int) -> int:
    """Return positive overlap in base pairs for two intervals."""
    return max(0, min(a_end, b_end) - max(a_start, b_start))


def distance_bp(a_start: int, a_end: int, b_start: int, b_end: int) -> int:
    """Return the BED half-open distance between two intervals.

    For non-overlapping BED intervals, the distance is the number of bases in
    the gap between the half-open endpoints.  For example, ``[0, 10)`` and
    ``[20, 30)`` are 10 bases apart.
    """
    if overlap_bp(a_start, a_end, b_start, b_end) > 0:
        return 0
    if a_end <= b_start:
        return b_start - a_end
    return a_start - b_end


def unique_join(values: Iterable[str]) -> str:
    """Join non-empty values preserving first occurrence order."""
    seen = set()
    out: List[str] = []
    for value in values:
        if value in {"", "."}:
            continue
        if value not in seen:
            seen.add(value)
            out.append(value)
    return ",".join(out) if out else "."


def write_table(
    path: Optional[Path],
    header: Sequence[str],
    rows: Iterable[Sequence[object]],
    include_header: bool = True,
) -> None:
    """Write a tab-delimited table to a file or stdout when ``path`` is None."""
    if path is None:
        writer = csv.writer(sys.stdout, delimiter="\t", lineterminator="\n")
        if include_header:
            writer.writerow(header)
        for row in rows:
            writer.writerow(list(row))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        if include_header:
            writer.writerow(header)
        for row in rows:
            writer.writerow(list(row))


def output_region_values(
    region: InputRegion,
    values: Sequence[object],
    output_format: str,
    region_column: int = 0,
) -> List[object]:
    """Return input values normalized for the requested output format."""
    original = list(values)
    if output_format in {"txt", "txtnohead"}:
        if len(original) >= 3 and str(original[0]) == region.chrom and str(original[1]) == str(region.start) and str(original[2]) == str(region.end):
            return [region.region_name] + original[3:]
        if 0 <= region_column < len(original):
            original[region_column] = region.region_name
        elif original:
            original[0] = region.region_name
        return original
    if output_format != "bed":
        return original
    if len(original) >= 3 and str(original[0]) == region.chrom and str(original[1]) == str(region.start) and str(original[2]) == str(region.end):
        original = original[3:]
    elif original and str(original[0]) == region.region_name:
        original = original[1:]
    return [region.chrom, region.start, region.end] + original


def output_region_header(header: Sequence[str], output_format: str) -> List[str]:
    """Return a header normalized for the requested output format."""
    if output_format in {"txt", "txtnohead"}:
        if len(header) >= 3 and header[1].lower() in {"start", "chromstart"} and header[2].lower() in {"end", "chromend"}:
            return ["Region"] + list(header[3:])
        if header and header[0].lower() in {"region", "coordinate", "coordinates"}:
            return ["Region"] + list(header[1:])
        return list(header)
    if output_format != "bed":
        return list(header)
    if len(header) >= 3 and header[1].lower() in {"start", "chromstart"} and header[2].lower() in {"end", "chromend"}:
        return ["chr", "start", "end"] + list(header[3:])
    return ["chr", "start", "end"] + list(header[1:])
