#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

# Generated by sjcab_peak2anno for review/reproduction.
# Input must be BED-like with chromosome/start/end in columns 1-3.
# Reference must contain TSS-like BED records with name, strand, and gene ID.
# Usage: ./bedtools-peak2anno.sh [1|2] [output.tsv]
MODE=${1:-2}
OUTPUT=${2:-peak2gene.bedtools.tsv}
INPUT=/research/rgs01/home/clusterHome/bxu2/tgz/pypi/sjcab_peak2anno/2.bed
REFERENCE=/research/rgs01/home/clusterHome/bxu2/.sjcab_peak2anno_db/bed/mm10/vM22/all.gene.bed
PROMOTER_UP=2000
ENHANCER=50000
PROMOTER_DOWN=2000

case "$MODE" in 1|2) ;; *) echo 'MODE must be 1 or 2' >&2; exit 2 ;; esac
command -v bedtools >/dev/null || { echo 'bedtools is required' >&2; exit 127; }
WORK=$(mktemp -d -t sjcab-peak2anno-script.XXXXXX)
trap 'rm -rf "$WORK"' EXIT
awk 'BEGIN{OFS="\t"} !/^#/ && NF >= 3 {print $1,$2,$3,NR}' "$INPUT" > "$WORK/query.bed"

# Emit query_id, class, reference_name, gene_id, distance.
classify_promoter='
BEGIN{OFS="\t"}
function abs(x){return x < 0 ? -x : x}
function max(a,b){return a > b ? a : b}
{
  qid=$4; rs=$6; re=$7; name=$8; strand=$10; gid=$11
  if ($3 <= rs) {d=rs-$3; side="left"} else if ($2 >= re) {d=$2-re; side="right"} else {d=0; side="overlap"}
  allowed=max(PROMOTER_UP,PROMOTER_DOWN)
  if (side == "left" && strand == "+") allowed=PROMOTER_UP
  if (side == "right" && strand == "+") allowed=PROMOTER_DOWN
  if (side == "left" && strand == "-") allowed=PROMOTER_DOWN
  if (side == "right" && strand == "-") allowed=PROMOTER_UP
  if (d <= allowed) print qid,"promoter",name,gid,d
}
'

if [[ "$MODE" == 1 ]]; then
  bedtools window -a "$WORK/query.bed" -b "$REFERENCE" -w "$((ENHANCER + 1))" \
    > "$WORK/wide.tsv"
  awk -v PROMOTER_UP="$PROMOTER_UP" -v PROMOTER_DOWN="$PROMOTER_DOWN" "$classify_promoter" "$WORK/wide.tsv" > "$WORK/promoters.tsv"
  cut -f1 "$WORK/promoters.tsv" | sort -nu > "$WORK/promoter_ids.txt"
  awk 'NR==FNR{seen[$1]=1; next} !($4 in seen)' "$WORK/promoter_ids.txt" "$WORK/wide.tsv" \
    | awk -v ENHANCER="$ENHANCER" 'BEGIN{OFS="\t"} {d=($3 <= $6 ? $6-$3+1 : ($2 >= $7 ? $2-$7+1 : 0)); if (d <= ENHANCER) print $4,"enhancer",$8,$11,d}' > "$WORK/enhancers.tsv"
else
  bedtools window -a "$WORK/query.bed" -b "$REFERENCE" -w "$(( (PROMOTER_UP > PROMOTER_DOWN ? PROMOTER_UP : PROMOTER_DOWN) + 1 ))" \
    | awk -v PROMOTER_UP="$PROMOTER_UP" -v PROMOTER_DOWN="$PROMOTER_DOWN" "$classify_promoter" > "$WORK/promoters.tsv"
  cut -f1 "$WORK/promoters.tsv" | sort -nu > "$WORK/promoter_ids.txt"
  awk 'NR==FNR{seen[$1]=1; next} !($4 in seen)' "$WORK/promoter_ids.txt" "$WORK/query.bed" > "$WORK/no_promoter.bed"
  bedtools window -a "$WORK/no_promoter.bed" -b "$REFERENCE" -w "$((ENHANCER + 1))" \
    | awk -v ENHANCER="$ENHANCER" 'BEGIN{OFS="\t"} {d=($3 <= $6 ? $6-$3+1 : ($2 >= $7 ? $2-$7+1 : 0)); if (d <= ENHANCER) print $4,"enhancer",$8,$11,d}' > "$WORK/enhancers.tsv"
fi
cat "$WORK/promoters.tsv" "$WORK/enhancers.tsv" > "$WORK/matches.tsv"
awk -F $'\t' 'BEGIN{OFS=FS} {print $1,$2,$3}' "$WORK/matches.tsv" | sort -t $'\t' -k1,1n -k2,2 -k3,3 -u | awk -F $'\t' 'BEGIN{OFS=FS} function flush(){if(qid!="") print qid,cat,value} {if($1!=qid || $2!=cat){flush(); qid=$1; cat=$2; value=$3} else {value=value (value=="" ? "" : ",") $3}} END{flush()}' > "$WORK/names.tsv"
awk -F $'\t' 'BEGIN{OFS=FS} {print $1,$2,$4}' "$WORK/matches.tsv" | sort -t $'\t' -k1,1n -k2,2 -k3,3 -u | awk -F $'\t' 'BEGIN{OFS=FS} function flush(){if(qid!="") print qid,cat,value} {if($1!=qid || $2!=cat){flush(); qid=$1; cat=$2; value=$3} else {value=value (value=="" ? "" : ",") $3}} END{flush()}' > "$WORK/ids.tsv"
bedtools closest -a "$WORK/query.bed" -b "$REFERENCE" -d -t first | awk '{print $4,$8,$11,$NF}' OFS=$'\t' > "$WORK/closest.tsv"
awk -F $'\t' -v OFS=$'\t' -v NAMES="$WORK/names.tsv" -v IDS="$WORK/ids.tsv" -v CLOSEST="$WORK/closest.tsv" '
BEGIN { while ((getline line < NAMES) > 0) { split(line,a,FS); names[a[1] SUBSEP a[2]]=a[3] } close(NAMES); while ((getline line < IDS) > 0) { split(line,a,FS); ids[a[1] SUBSEP a[2]]=a[3] } close(IDS); while ((getline line < CLOSEST) > 0) { split(line,a,FS); closest[a[1]]=a[2]; closest_id[a[1]]=a[3]; closest_dist[a[1]]=a[4] } close(CLOSEST) }
{ q=$4; p=names[q SUBSEP "promoter"]; if(p=="") p="."; pi=ids[q SUBSEP "promoter"]; if(pi=="") pi="."; e=names[q SUBSEP "enhancer"]; if(e=="") e="."; ei=ids[q SUBSEP "enhancer"]; if(ei=="") ei="."; g=closest[q]; if(g=="") g="."; gi=closest_id[q]; if(gi=="") gi="."; d=closest_dist[q]; if(d=="") d="."; print $1,$2,$3,p,pi,e,ei,g,gi,d }' "$WORK/query.bed" > "$WORK/body.tsv"
printf 'chr\tstart\tend\tGene_%skb\tGencode_ids\tGene_%s-%skb\tGencode_ids\tClosest_Gene\tGencode_id\tDistance\n' "$((PROMOTER_UP / 1000))" "$((PROMOTER_UP / 1000))" "$((ENHANCER / 1000))" > "$OUTPUT"
cat "$WORK/body.tsv" >> "$OUTPUT"
echo "Wrote $OUTPUT" >&2
